version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/taxProject  # localの.とdockerコンテナの/usr~Projectを同期
      # exclude volumes(空のhogeをマウントさせる)
      - hoge:/usr/src/taxProject/app/vendor
      - hoge:/usr/src/taxProject/app/tmp
      - hoge:/usr/src/taxProject/app/log
      - hoge:/usr/src/taxProject/app/.git

    links:
      - mysql
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
  hoge:
